module.exports = {
  login: {
    baseUrl: 'https://demo.tradingdocs.ai',
    loginPath: '/login',
    homePath: '/',
    selectors: {
      emailInput: 'input[name="email"]',
      passwordInput: 'input[name="password"]',
      submitButton: 'button[type="submit"]',
    },
    timeouts: {
      navigation: 10000,
      postLoginRedirect: 10000,
    },
  },
  shipment: {
    baseUrl: 'https://demo.tradingdocs.ai',
    shipmentsPath: '/shipments',
    selectors: {
      addButton: 'button#grid_1979692032_0_add',
      modal: '.e-dialog.e-popup-open[role="dialog"]',
      shipmentIdInput: 'input#shipmentId',
      shipperInput: 'input#shipper',
      consigneeInput: 'input#consignee',
      statusDropdownIcon: '.e-input-group-icon.e-ddl-icon.e-search-icon',
      statusPopup: '#status_popup',
      statusOptionGenerated: '#status_popup .e-list-item',
      blNumberInput: 'input#blNumber',
      commodityInput: 'input#commodity',
      originPortInput: 'input#originPort',
      destinationPortInput: 'input#destinationPort',
      vesselNameInput: 'input#vesselName',
      shipmentDateInput: 'input#shipmentDate',
      etdInput: 'input#etd',
      etaInput: 'input#eta',
      bookingNumberInput: 'input#bookingNumber',
      referenceInput: 'input#reference',
      saveButton: 'button:has-text("Save")',
      editButton: 'button#grid_1979692032_0_edit',
      updateButton: 'button.update-shipment-data',
      shipmentSavedPopupSelector: 'div.e-alert-dialog.e-popup-open',
      shipmentSavedPopupOkButtonSelector: 'button.predefined-dialog',
      shipmentSavedPopupSuccessMessageSelector: 'div.dialog-text > h2',
      deleteButton: 'button#grid_1979692032_0_delete',
      deleteConfirmPopup: 'div.e-dialog.e-popup-open[role="dialog"]',
      deleteConfirmOkButton: 'div.e-footer-content button.e-primary:has-text("OK")',
      gridRowCheckbox: 'div.e-gridcontent tbody tr.e-row td .e-checkselect',
      confirmDeletePopup: '.e-confirm-dialog.e-popup-open',
      confirmDeleteButton: '.e-confirm-dialog.e-popup-open .e-footer-content button.e-primary',
    },
    data: {
      shipmentId: 'TEST-001',
      shipper: 'Test Shipper',
      consignee: 'Test Consignee',
      blNumber: 'BL123456',
      newBLNumber: 'BL654321',
      commodity: 'Steel',
      originPort: 'Istanbul',
      destinationPort: 'Dubai',
      vesselName: 'Black Pearl',
      shipmentDate: '07/15/2025',
      etd: '07/15/2025',
      eta: '07/25/2025',
      bookingNumber: 'BOOK1234',
      reference: 'Test Reference',
      expectedSuccessText: 'Success',
      statusOption: 'Generated', // Burada dropdown seçeneği olarak status'u belirttik
    },
    timeouts: {
      pageLoad: 10000,
      buttonVisible: 5000,
      modalVisible: 5000,
      inputVisible: 5000,
      statusPopupVisible: 5000,
      statusOptionVisible: 5000,
      modalOpen: 10000,
      modalClose: 10000,
      shipmentSavedPopupTimeout: 10000,
    },
  },
  extractors: {
    baseUrl: 'https://demo.tradingdocs.ai/extractors',
    data: {
      extractorName: 'Test Extractor',
      description: 'This is a test extractor.',
      isActive: 'Y',
    },
    selectors: {
      pageTitle: 'h3.page-title',
      addButton: 'button.e-tbar-btn:has-text("Add")',
      extractorNameInput: 'input#extractorName',
      descriptionInput: 'input#description',
      activeDropdownIcon: 'div.e-control-wrapper .e-ddl-icon',
      entitiesAddButton: 'button.e-tbar-btn[aria-label="Add"]',
      entitiesModal: '#entityModal',
      mainSaveButton: 'button.submit-button:has-text("Save")',
    },
    timeouts: {
      navigation: 10000,
      dropdown: 5000,
      input: 5000,
      modal: 5000,
    },
  },
  ruleset: {
    baseUrl: 'https://demo.tradingdocs.ai',
    rulesetsPath: '/rulesets',
    selectors: {
      pageTitle: 'text=Rulesets',
      addButton: 'span.e-tbar-btn-text:has-text("Add")',
      editButton: 'button#grid_1216849542_0_edit',
      rulesetNameInput: '#rulesetName',
      rulesetDescriptionInput: '#rulesetDescription',
      commodityInput: '#commodity',
      destinationCountryInput: '#destinationCountry',
      originCountryInput: '#originCountry',
      effectiveDateInput: '#effectiveDate',
      rulesetSourceInput: '#rulesetSource',
      rulesInput: '#rules',
      rulesetTypeDropdownIcon: '#rulesetType ~ .e-input-group-icon.e-ddl-icon',
      rulesetTypePopup: '#rulesetType_popup',
      rulesetTypeListItem: '#rulesetType_popup .e-list-item',
      metadataAccordion: '.e-acrdn-header:has-text("Metadata")',
      isActiveDropdown: '#isActive',
      isActiveDropdownIcon: '#isActive ~ .e-input-group-icon.e-ddl-icon',
      isActivePopup: '#isActive_popup',
      isActiveListItem: '#isActive_popup .e-list-item',
      isActiveYOption: '#isActive_popup .e-list-item:has-text("Y")',
      saveButton: 'button.e-edit-dialog.submit-button',
      successText: 'text=Test Ruleset',
      deleteButton: 'div[title="Delete"] button',
      deleteConfirmPopup: '#confirmPopup',
      deleteConfirmOkButton: 'div.e-confirm-dialog.e-popup-open div.e-footer-content button.e-primary:has-text("OK")',
      tableRow: 'div.e-gridcontent tr.e-row',
    },
    rulesetData: {
      rulesetName: 'Test Ruleset',
      rulesetDescription: 'Automatically created via Playwright',
      commodity: 'Steel',
      destinationCountry: 'UAE',
      originCountry: 'Turkey',
      effectiveDate: '07/14/2025',
      rulesetSource: 'Auto Test',
      rules: 'IF commodity == "Steel" THEN apply tax',
      rulesetTypeOption: 'Commodity',  // Dropdown seçeneği config'de burada
      isActiveOption: 'Y',
    },
    timeouts: {
      pageLoad: 10000,
      formVisible: 5000,
      inputFillDelay: 100,
      beforeDropdownSelection: 500,
      dropdownVisible: 5000,
      dropdownSettle: 500,
      beforeAccordion: 500,
      accordionAnimation: 500,
      beforeSave: 300,
      successVisible: 10000,
      navigation: 10000,
      selector: 5000,
    },
  },
};
