/*
1-Create a solid config file and have static values inside of it so that if anything changes it'd be easier to fix.
2-Enlarge the scope of project to Create-Edit-Delete files.
3-If you are using the same logic for same things, just turn them into a function in utils folder like popoverHandler. (could be done with modals and dropdowns.)
4-Trim the config.js file I don't think anyone really needs a file as large as that one..
5-Have all this ready for tomorrow 6PM.
*/